#include "CorePCH.hpp"
#include "RTTI.hpp"

RTTI_DEFINE_PRIMITIVE_TYPE(bool)
RTTI_DEFINE_PRIMITIVE_TYPE(i8)
RTTI_DEFINE_PRIMITIVE_TYPE(i16)
RTTI_DEFINE_PRIMITIVE_TYPE(i32)
RTTI_DEFINE_PRIMITIVE_TYPE(i64)
RTTI_DEFINE_PRIMITIVE_TYPE(u8)
RTTI_DEFINE_PRIMITIVE_TYPE(u16)
RTTI_DEFINE_PRIMITIVE_TYPE(u32)
RTTI_DEFINE_PRIMITIVE_TYPE(u64)
RTTI_DEFINE_PRIMITIVE_TYPE(f32)
RTTI_DEFINE_PRIMITIVE_TYPE(f64)

//RTTI_DEFINE_PRIMITIVE_TYPE(int)
//RTTI_DEFINE_PRIMITIVE_TYPE(uint)

RTTI_DEFINE_TYPE(Poly::RTTIBase)